[package]
name = "db-migration"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm-migration = { version = "2.0.0-rc.28", features = ["runtime-tokio-rustls", "sqlx-sqlite", "sqlx-postgres"] }
async-trait = { workspace = true }
tokio = { workspace = true }
